train:
  _target_: src.datasets.CIFARDataset
  dataset: "cifar10"
  name: "train"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.CIFARDataset
  dataset: "cifar10"
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
