train:
  _target_: src.datasets.STLDataset
  name: "train"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.STLDataset
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
