# TODO fix this, probably bug with apply augs on tensor instead of image)
train:
  img:
    _target_: src.transforms.BatchSequential
    _args_:
      - _target_: src.transforms.LightlySingleView
        view_index: 0
        transform:
          _target_: lightly.transforms.DINOTransform
          global_crop_size: 96
          local_crop_size: 32
          n_local_views: 6
          cj_prob: 0.8
          gaussian_blur: [1.0, 0.1, 0.5]
          solarization_prob: 0.2
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5, ]
        std: [0.5, ]

inference:
  img:
    _target_: src.transforms.BatchSequential
    _args_:
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5, ]
        std: [0.5, ]

