train:
  aug:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: transforms.DropDigit
        p: 0.5
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]

inference:
  img:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]
