train:
  aug1:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.v2.RandomResizedCrop
        size: 32
        scale: [0.2, 1.0]
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      - _target_: torchvision.transforms.v2.RandomApply
        p: 0.8
        transforms:
          - _target_: torchvision.transforms.v2.ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
      - _target_: torchvision.transforms.v2.RandomGrayscale
        p: 0.2
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]
  aug2:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.v2.RandomResizedCrop
        size: 32
        scale: [0.2, 1.0]
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      - _target_: torchvision.transforms.v2.RandomApply
        p: 0.8
        transforms:
          - _target_: torchvision.transforms.v2.ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
      - _target_: torchvision.transforms.v2.RandomGrayscale
        p: 0.2
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]

inference:
  img:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.v2.ToTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]
