defaults:
  - model: resnet
  - metrics: accuracy
  - datasets: mnist_test
  - dataloader: main
  - transforms: main
  - _self_
inferencer:
  device_tensors: ["img", "labels"]
  device: auto
  save_path: null
  seed: 1
  from_pretrained: null
