defaults:
  - model: probe_pre_mlp_coarse
  - writer: cometml
  - metrics: accuracy
  - datasets: cifar100coarse
  - dataloader: main
  - transforms: cifar100_probing
  - _self_

dataloader:
  batch_size: 512

optimizer:
  _target_: torch.optim.SGD
  lr: 1e-1
  momentum: 0.9
  weight_decay: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1.0
loss_function:
  _target_: src.loss.CrossEntropyLoss
trainer:
  log_step: 50
  n_epochs: 50
  epoch_len: null
  device_tensors: ["img", "labels"]
  resume_from: null
  device: auto
  override: False
  monitor: "max test_Accuracy"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
  linear_probing: True
  from_pretrained: content/scl_pretrain_resnet_mlp.pth
  training_mode: "probing"

