defaults:
  - model: resnet_ssl_pretrain_mlp
  - writer: cometml
  - metrics: dummy
  - datasets: mnist_on_cifar10
  - dataloader: main
  - transforms: mnist_on_cifar
  - _self_

dataloader:
  batch_size: 512

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-6
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1.0
loss_function:
  _target_: src.loss.SimCLRLoss
  temperature: 0.5
trainer:
  log_step: 50
  n_epochs: 400
  epoch_len: null
  device_tensors: ["labels", "aug1", "aug2", "digit"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 40 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  training_mode: "CL"
