defaults:
  - model: vit_scl_pretrain_mlp
  - writer: cometml
  - metrics: dummy
  - datasets: cifar100coarse
  - dataloader: main
  - transforms: scl_pretrain
  - _self_

dataloader:
  batch_size: 1600

optimizer:
  _target_: torch.optim.SGD
  lr: 0.2
  momentum: 0.9
  weight_decay: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 0.2       # Должен совпадать с optimizer.lr
  epochs: 300
  steps_per_epoch: 32 # 50000 / 1600 = 31.25 (округляем вверх)
  pct_start: 0.1    # 10% времени (30 эпох) на разогрев
  div_factor: 100   # Начнем с LR = 0.2 / 100 = 0.002 (безопасно!)
  final_div_factor: 1000 # В конце опустим почти до нуля

loss_function:
  _target_: src.loss.SupConLoss
  temperature: 0.5
trainer:
  log_step: 50
  n_epochs: 300
  epoch_len: null
  device_tensors: ["labels", "aug1", "aug2"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 40 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  training_mode: "CL"
